# 로컬 테스트용 Docker-compose

version: "3"
services:
  dev:
    image: 751264546625.dkr.ecr.ap-northeast-2.amazonaws.com/depromeet-final-ecr:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - 8000:8000