spring:
  profiles:
    active: local
    include:
      - domain
      - s3
      - aws
  datasource:
    data: classpath:schema/schema-session.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8000