name: Deploy Dev Server

on:
  push:
    branches: [ develop ]
env:
  PROJECT_NAME: month-app
  BUCKET_NAME: depromeet-final-bucket
  BUCKET_REGION: ap-northeast-2
  CODE_DEPLOY_APP: depromeet-final-backend
  CODE_DEPLOY_GROUP: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase-admin.json"
          json: ${{ secrets.FIREBASE_ADMIN_JSON }}
          dir: 'month-external/src/main/resources/'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make deploy/month-app/build/libs/
        run: mkdir -p deploy/month-app/build/libs/

      - name: Make deploy/scripts
        run: mkdir -p deploy/scripts/

      - name: Copy appspec.yml into deploy/
        run: cp appspec.yml deploy/

      - name: Copy *.jar into deploy/
        run: cp month-app/build/libs/*.jar deploy/month-app/build/libs/

      - name: Copy Dockerfile into deploy/
        run: cp Dockerfile deploy/

      - name: Copy docker-compose.*.yml into deploy/
        run: cp docker-compose.*.yml deploy/

      - name: Copy run.sh into deploy/
        run: cp ./scripts/run.sh deploy/scripts/

      - name: Zip deploy/
        run: zip -r deploy.zip deploy/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://${BUCKET_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip --region ${BUCKET_REGION}

      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${CODE_DEPLOY_APP} --deployment-group-name ${CODE_DEPLOY_GROUP} --s3-location bucket=${BUCKET_NAME},bundleType=zip,key=${PROJECT_NAME}-${GITHUB_SHA}.zip